
FAIL a signal argument 'null' should cause pipeTo() to reject |this| is not a Promise
FAIL a signal argument 'AbortSignal' should cause pipeTo() to reject |this| is not a Promise
FAIL a signal argument 'true' should cause pipeTo() to reject |this| is not a Promise
FAIL a signal argument '-1' should cause pipeTo() to reject |this| is not a Promise
FAIL a signal argument '[object AbortSignal]' should cause pipeTo() to reject |this| is not a Promise
FAIL an aborted signal should cause the writable stream to reject with an AbortError |this| is not a Promise
FAIL all the AbortError objects should be the same object |this| is not a Promise
FAIL preventCancel should prevent canceling the readable |this| is not a Promise
FAIL preventAbort should prevent aborting the readable |this| is not a Promise
FAIL preventCancel and preventAbort should prevent canceling the readable and aborting the readable |this| is not a Promise
FAIL abort should prevent further reads |this| is not a Promise
FAIL all pending writes should complete on abort |this| is not a Promise
FAIL a rejection from underlyingSource.cancel() should be returned by pipeTo() |this| is not a Promise
FAIL a rejection from underlyingSink.abort() should be returned by pipeTo() |this| is not a Promise
FAIL a rejection from underlyingSink.abort() should be preferred to one from underlyingSource.cancel() |this| is not a Promise
FAIL abort signal takes priority over closed readable |this| is not a Promise
FAIL abort signal takes priority over errored readable |this| is not a Promise
FAIL abort signal takes priority over closed writable promise_test: Unhandled rejection with value: object "TypeError: |this| is not a Promise"
FAIL abort signal takes priority over errored writable |this| is not a Promise
FAIL abort should do nothing after the readable is closed |this| is not a Promise
FAIL abort should do nothing after the readable is errored |this| is not a Promise
FAIL abort should do nothing after the readable is errored, even with pending writes |this| is not a Promise
FAIL abort should do nothing after the writable is errored |this| is not a Promise

